
spring:
  application:
    name: ocr
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

logging:
  level:
    org.springframework.web: INFO
    at.fhtw.rest: INFO
    org.zalando.logbook: TRACE

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

elasticsearch:
  url: ${ELASTICSEARCH_URL}
  index: ${ELASTICSEARCH_INDEX}

server:
  port: 8081
